import type { Property } from './types';

// NOTE: This is a placeholder UID. In a real application, this would be the
// actual Firebase Auth UID of the owner 'sankichore@gmail.com'.
const SANKI_CHORE_UID = 'sankichore_owner_uid_placeholder';


export const properties: Property[] = [
  {
    id: 'prop1',
    title: 'Modern Boys Hostel in Sector 62',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'modern hostel',
    price: 14000,
    location: 'Sector 62, Near Metro Station',
    city: 'Noida',
    rating: 4.8,
    reviews: 112,
    type: 'Boys',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food', 'Laundry', 'Housekeeping'],
    description: 'A premium hostel for boys with state-of-the-art facilities, located in the heart of the institutional area in Sector 62.',
    roomOptions: [
      { occupancy: 'Double', price: 14000 },
      { occupancy: 'Single', price: 20000 },
    ],
    map: { lat: 28.618, lng: 77.371, nearby: [{ name: 'Noida Sector 62 Metro', distance: '500m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop2',
    title: 'Secure Girls PG in Knowledge Park III',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'girls pg room',
    price: 9500,
    location: 'Knowledge Park III, Near Sharda University',
    city: 'Greater Noida',
    rating: 4.5,
    reviews: 89,
    type: 'Girls',
    category: 'PG',
    amenities: ['WiFi', 'Food', 'CCTV', 'Geyser'],
    description: 'Safe and comfortable PG for girls with home-style food and 24/7 security. Walking distance from major colleges.',
    roomOptions: [
      { occupancy: 'Triple', price: 9500 },
      { occupancy: 'Double', price: 11500 },
    ],
    map: { lat: 28.4744, lng: 77.5050, nearby: [{ name: 'Sharda University', distance: '1km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop3',
    title: 'Co-living Space for Professionals, Sec 137',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'professional coliving',
    price: 18000,
    location: 'Sector 137, Near Advant Navis Business Park',
    city: 'Noida',
    rating: 4.9,
    reviews: 205,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'AC', 'Housekeeping', 'Parking', 'Laundry'],
    description: 'Fully furnished private rooms for working professionals with a vibrant community, networking events, and all-inclusive bills.',
    roomOptions: [{ occupancy: 'Single', price: 18000 }],
    map: { lat: 28.508, lng: 77.411, nearby: [{ name: 'Advant IT Park', distance: '800m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop4',
    title: 'Budget PG for Boys in Alpha 1',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'budget pg',
    price: 8000,
    location: 'Alpha 1, Near Metro',
    city: 'Greater Noida',
    rating: 3.9,
    reviews: 45,
    type: 'Boys',
    category: 'PG',
    amenities: ['Food', 'Geyser', 'Parking'],
    description: 'Affordable PG accommodation for boys with all basic necessities covered. Great for students on a tight budget.',
    roomOptions: [
      { occupancy: 'Triple', price: 8000 },
      { occupancy: 'Double', price: 9500 },
    ],
    map: { lat: 28.464, lng: 77.514, nearby: [{ name: 'Alpha 1 Metro', distance: '600m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop5',
    title: 'Luxury Girls Hostel, Sector 125',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'luxury hostel',
    price: 17000,
    location: 'Sector 125, Near Amity University',
    city: 'Noida',
    rating: 4.7,
    reviews: 150,
    type: 'Girls',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food', 'Laundry', 'CCTV', 'Housekeeping'],
    description: 'A high-end hostel for girls with premium amenities including a gym, common lounge, and enhanced security features.',
    roomOptions: [
      { occupancy: 'Double', price: 17000 },
      { occupancy: 'Single', price: 25000 },
    ],
    map: { lat: 28.543, lng: 77.333, nearby: [{ name: 'Amity University', distance: '400m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop6',
    title: 'Private Room in Gated Society',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'private room',
    price: 11000,
    location: 'Omega II, Greater Noida',
    city: 'Greater Noida',
    rating: 4.3,
    reviews: 32,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['AC', 'Parking', 'Housekeeping', 'Geyser'],
    description: 'A clean and private room in a secure, gated residential society. Suitable for students or professionals seeking a quiet environment.',
    roomOptions: [{ occupancy: 'Single', price: 11000 }],
    map: { lat: 28.45, lng: 77.51, nearby: [{ name: 'YMCA', distance: '1.5km' }] },
    status: 'pending',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop7',
    title: 'Affordable Co-ed PG in Sector 15',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'affordable pg',
    price: 7000,
    location: 'Sector 15, Noida',
    city: 'Noida',
    rating: 3.5,
    reviews: 67,
    type: 'Co-ed',
    category: 'PG',
    amenities: ['WiFi', 'Food', 'Laundry'],
    description: 'No-frills PG for students and young professionals. A lively place with good connectivity to Delhi.',
    roomOptions: [{ occupancy: 'Triple', price: 7000 }],
    map: { lat: 28.583, lng: 77.317, nearby: [{ name: 'Sector 15 Metro', distance: '300m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop8',
    title: 'Short-Stay Hotel Room, Sector 18',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'hotel room',
    price: 25000,
    location: 'Sector 18, Near DLF Mall',
    city: 'Noida',
    rating: 4.1,
    reviews: 130,
    type: 'Co-ed',
    category: 'Hotel',
    amenities: ['WiFi', 'AC', 'Housekeeping', 'Food'],
    description: 'A comfortable hotel room available for monthly stays. Perfect for corporate clients or people in transition. No kitchen.',
    roomOptions: [{ occupancy: 'Single', price: 25000 }],
    map: { lat: 28.57, lng: 77.323, nearby: [{ name: 'DLF Mall of India', distance: '500m' }] },
    status: 'rejected',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop9',
    title: 'Student Hostel near Galgotias',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'student hostel',
    price: 10000,
    location: 'Knowledge Park II, Greater Noida',
    city: 'Greater Noida',
    rating: 4.4,
    reviews: 95,
    type: 'Co-ed',
    category: 'Hostel',
    amenities: ['WiFi', 'Food', 'Geyser', 'CCTV'],
    description: 'A bustling student hostel just a stone\'s throw away from Galgotias University. Includes meals and weekly cleaning.',
    roomOptions: [
      { occupancy: 'Triple', price: 10000 },
      { occupancy: 'Double', price: 12000 },
    ],
    map: { lat: 28.47, lng: 77.498, nearby: [{ name: 'Galgotias University', distance: '700m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop10',
    title: 'Executive PG for Men',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'executive pg',
    price: 16000,
    location: 'Sector 50, Noida',
    city: 'Noida',
    rating: 4.6,
    reviews: 72,
    type: 'Boys',
    category: 'PG',
    amenities: ['WiFi', 'AC', 'Food', 'Parking', 'Housekeeping'],
    description: 'A PG designed for working men, offering spacious rooms, high-speed internet, and quality food. Close to the Sector 50 metro station.',
    roomOptions: [
      { occupancy: 'Double', price: 16000 },
      { occupancy: 'Single', price: 22000 },
    ],
    map: { lat: 28.57, lng: 77.36, nearby: [{ name: 'Noida Sector 50 Metro', distance: '1km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop11',
    title: 'Quiet Room for Creatives',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'quiet room',
    price: 13000,
    location: 'Pari Chowk, Greater Noida',
    city: 'Greater Noida',
    rating: 4.8,
    reviews: 21,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'Housekeeping'],
    description: 'A serene and peaceful room with minimal distractions. Ideal for writers, designers, or anyone needing a quiet space to focus.',
    roomOptions: [
        { occupancy: 'Single', price: 13000 }
    ],
    map: { lat: 28.468, lng: 77.513, nearby: [{ name: 'Pari Chowk Metro', distance: '1.2km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop12',
    title: 'Girls PG with Balcony',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'room balcony',
    price: 11000,
    location: 'Sector 27, Noida',
    city: 'Noida',
    rating: 4.2,
    reviews: 55,
    type: 'Girls',
    category: 'PG',
    amenities: ['WiFi', 'AC', 'Geyser', 'CCTV'],
    description: 'Bright and airy rooms with private balconies. A comfortable and safe choice for female students and professionals.',
    roomOptions: [
        { occupancy: 'Double', price: 11000 }
    ],
    map: { lat: 28.577, lng: 77.33, nearby: [{ name: 'Sector 18 Market', distance: '800m' }] },
    status: 'pending',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop13',
    title: 'All-Inclusive Student Hostel',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'student hostel',
    price: 15000,
    location: 'Knowledge Park V, Greater Noida',
    city: 'Greater Noida',
    rating: 4.6,
    reviews: 180,
    type: 'Boys',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food', 'Laundry', 'Housekeeping', 'Geyser', 'CCTV'],
    description: 'Everything included! Just move in and focus on your studies. All bills, food, and laundry are covered in the monthly rent.',
    roomOptions: [
      { occupancy: 'Triple', price: 15000 }
    ],
    map: { lat: 28.51, lng: 77.42, nearby: [{ name: 'GNIOT Group of Institutions', distance: '2km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop14',
    title: 'Room near Film City',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'modern room',
    price: 9000,
    location: 'Sector 16A, Noida',
    city: 'Noida',
    rating: 4.0,
    reviews: 41,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'Parking'],
    description: 'Basic accommodation near Film City, ideal for interns or media professionals on short-term projects.',
    roomOptions: [
      { occupancy: 'Double', price: 9000 }
    ],
    map: { lat: 28.58, lng: 77.31, nearby: [{ name: 'Noida Film City', distance: '1km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop15',
    title: 'Home-style PG for Girls',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'home style pg',
    price: 12500,
    location: 'Beta I, Greater Noida',
    city: 'Greater Noida',
    rating: 4.9,
    reviews: 92,
    type: 'Girls',
    category: 'PG',
    amenities: ['WiFi', 'AC', 'Food', 'Housekeeping', 'Laundry'],
    description: 'Run by a family, this PG offers a true home-away-from-home experience with delicious meals and a caring environment.',
    roomOptions: [
      { occupancy: 'Double', price: 12500 }
    ],
    map: { lat: 28.46, lng: 77.51, nearby: [{ name: 'Beta 1 Metro', distance: '900m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop16',
    title: 'Hostel for Medical Students',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'medical student hostel',
    price: 13000,
    location: 'Sector 30, Near Kailash Hospital',
    city: 'Noida',
    rating: 4.5,
    reviews: 61,
    type: 'Co-ed',
    category: 'Hostel',
    amenities: ['WiFi', 'Food', 'Geyser', 'CCTV'],
    description: 'A hostel specifically catering to medical students and hospital interns, offering a quiet study environment and proximity to major hospitals.',
    roomOptions: [
      { occupancy: 'Double', price: 13000 }
    ],
    map: { lat: 28.57, lng: 77.33, nearby: [{ name: 'Kailash Hospital', distance: '300m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop17',
    title: 'PG near Greater Noida Depot',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'pg exterior',
    price: 8500,
    location: 'Near Depot Station, Greater Noida',
    city: 'Greater Noida',
    rating: 4.0,
    reviews: 29,
    type: 'Boys',
    category: 'PG',
    amenities: ['Food', 'Parking'],
    description: 'Conveniently located near the main bus depot, this PG is perfect for those who travel frequently. Basic, clean, and affordable.',
    roomOptions: [
      { occupancy: 'Triple', price: 8500 }
    ],
    map: { lat: 28.47, lng: 77.52, nearby: [{ name: 'Depot Metro Station', distance: '400m' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop18',
    title: 'Independent Studio Apartment',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'studio apartment',
    price: 19000,
    location: 'Sector 75, Noida',
    city: 'Noida',
    rating: 4.7,
    reviews: 88,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'AC', 'Parking', 'Housekeeping'],
    description: 'A fully furnished studio apartment with a kitchenette. Offers complete privacy and is suitable for couples or individuals.',
    roomOptions: [
      { occupancy: 'Single', price: 19000 }
    ],
    map: { lat: 28.56, lng: 77.38, nearby: [{ name: 'Sector 50 Metro', distance: '1.5km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop19',
    title: 'Girls Hostel in a Safe Locality',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'safe girls hostel',
    price: 14500,
    location: 'Gamma I, Greater Noida',
    city: 'Greater Noida',
    rating: 4.9,
    reviews: 102,
    type: 'Girls',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food', 'CCTV', 'Laundry'],
    description: 'Our top priority is safety. Located in a secure residential area with a dedicated female warden and robust security systems.',
    roomOptions: [
      { occupancy: 'Double', price: 14500 }
    ],
    map: { lat: 28.45, lng: 77.5, nearby: [{ name: 'Jagannath Institute of Management', distance: '1km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop20',
    title: 'Corporate Guest House (Monthly)',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'corporate guesthouse',
    price: 30000,
    location: 'Sector 44, Noida',
    city: 'Noida',
    rating: 4.5,
    reviews: 40,
    type: 'Co-ed',
    category: 'Hotel',
    amenities: ['WiFi', 'AC', 'Food', 'Parking', 'Housekeeping', 'Laundry'],
    description: 'Hotel-like rooms available for monthly corporate bookings. Includes breakfast and dinner, daily housekeeping, and laundry service.',
    roomOptions: [
      { occupancy: 'Single', price: 30000 }
    ],
    map: { lat: 28.56, lng: 77.34, nearby: [{ name: 'Botanical Garden Metro', distance: '1km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop21',
    title: 'Basic Room for Rent',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'basic room',
    price: 6500,
    location: 'Swarn Nagri, Greater Noida',
    city: 'Greater Noida',
    rating: 3.7,
    reviews: 15,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['Parking', 'Geyser'],
    description: 'An unfurnished room for rent at a very low price. Tenant needs to arrange for their own amenities. Water and electricity included.',
    roomOptions: [
      { occupancy: 'Single', price: 6500 }
    ],
    map: { lat: 28.44, lng: 77.51, nearby: [{ name: 'Gautam Buddha University', distance: '3km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
  {
    id: 'prop22',
    title: 'Twin Sharing PG for Boys',
    image: 'https://placehold.co/600x400.png',
    images: ['https://placehold.co/800x600.png'],
    dataAiHint: 'twin sharing pg',
    price: 9000,
    location: 'Sector 34, Noida',
    city: 'Noida',
    rating: 4.1,
    reviews: 76,
    type: 'Boys',
    category: 'PG',
    amenities: ['WiFi', 'Food', 'Laundry', 'CCTV'],
    description: 'A well-managed PG exclusively offering twin-sharing rooms for boys. Close to City Centre and metro connectivity.',
    roomOptions: [
      { occupancy: 'Double', price: 9000 }
    ],
    map: { lat: 28.58, lng: 77.35, nearby: [{ name: 'Noida City Centre Metro', distance: '1.2km' }] },
    status: 'approved',
    ownerId: SANKI_CHORE_UID,
  },
];


export const allAmenities: ('WiFi' | 'AC' | 'Food' | 'Parking' | 'Laundry' | 'Geyser' | 'Housekeeping' | 'CCTV')[] = ['WiFi', 'AC', 'Food', 'Parking', 'Laundry', 'Geyser', 'Housekeeping', 'CCTV'];
export const allCategories: ('Hostel' | 'PG' | 'Room' | 'Hotel')[] = ['Hostel', 'PG', 'Room', 'Hotel'];
export const allCities = [
  // Delhi NCR
  'Delhi', 'Noida', 'Greater Noida', 'Gurgaon', 'Faridabad', 'Ghaziabad',
  // Major Metros
  'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad',
  // Tier-2 Cities
  'Jaipur', 'Lucknow', 'Chandigarh', 'Indore', 'Kochi', 'Coimbatore',
  'Bhopal', 'Nagpur', 'Vadodara', 'Thiruvananthapuram', 'Visakhapatnam',
  'Patna', 'Dehradun', 'Mangalore', 'Mysore', 'Surat', 'Ranchi',
  'Bhubaneswar', 'Goa', 'Pondicherry', 'Agra', 'Varanasi',
];
