import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Cozy Student Room near Campus',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'student room',
    price: 8500,
    location: 'Knowledge Park III, Greater Noida',
    city: 'Greater Noida',
    rating: 4.5,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'AC'],
    description: 'A cozy and fully furnished room perfect for students looking for a quiet place to study and relax. Located just minutes away from the main campus.',
  },
  {
    id: '2',
    title: 'Modern Boys Hostel with Food',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'modern hostel',
    price: 12000,
    location: 'Sector 62, Noida',
    city: 'Noida',
    rating: 4.8,
    type: 'Boys',
    category: 'Hostel',
    amenities: ['WiFi', 'Food', 'Parking'],
    description: 'State-of-the-art hostel for boys with all modern amenities. Includes three meals a day and high-speed internet. Secure and comfortable.',
  },
  {
    id: '3',
    title: 'Spacious Girls PG with AC',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'spacious room',
    price: 10000,
    location: 'Alpha I, Greater Noida',
    city: 'Greater Noida',
    rating: 4.2,
    type: 'Girls',
    category: 'PG',
    amenities: ['WiFi', 'AC', 'Food'],
    description: 'A safe and spacious paying guest accommodation for girls. Features air-conditioned rooms and home-style food. 24/7 security.',
  },
  {
    id: '4',
    title: 'Budget Hotel for Short Stays',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'budget hotel',
    price: 15000,
    location: 'Sector 18, Noida',
    city: 'Noida',
    rating: 4.0,
    type: 'Co-ed',
    category: 'Hotel',
    amenities: ['WiFi', 'AC', 'Parking'],
    description: 'Comfortable and affordable hotel rooms for short-term stays. Ideal for students and employees visiting for exams or interviews.',
  },
  {
    id: '5',
    title: 'Premium Student Hostel',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'premium hostel',
    price: 18000,
    location: 'Knowledge Park II, Greater Noida',
    city: 'Greater Noida',
    rating: 4.9,
    type: 'Co-ed',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food', 'Parking'],
    description: 'Experience luxury living in our premium student hostel. Comes with a gym, recreational areas, and top-notch security.',
  },
  {
    id: '6',
    title: 'Affordable PG for Students',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'student pg',
    price: 7500,
    location: 'Sector 12, Noida',
    city: 'Noida',
    rating: 3.8,
    type: 'Boys',
    category: 'PG',
    amenities: ['WiFi', 'Food'],
    description: 'A budget-friendly PG for male students. Clean rooms, decent food, and a friendly environment. Close to the metro station.',
  },
  {
    id: '7',
    title: 'Independent Room for Professionals',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'independent room',
    price: 11000,
    location: 'Beta II, Greater Noida',
    city: 'Greater Noida',
    rating: 4.6,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'AC', 'Parking'],
    description: 'A private, independent room suitable for working professionals or students who value their privacy. Includes a personal kitchenette.',
  },
  {
    id: '8',
    title: 'Girls Hostel near Metro',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'girls hostel',
    price: 13500,
    location: 'Sector 15, Noida',
    city: 'Noida',
    rating: 4.7,
    type: 'Girls',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food'],
    description: 'A well-maintained hostel for girls with excellent connectivity. Located just a 5-minute walk from the metro station. Safe and secure.',
  },
];

export const allAmenities: ('WiFi' | 'AC' | 'Food' | 'Parking')[] = ['WiFi', 'AC', 'Food', 'Parking'];
export const allCategories: ('Hostel' | 'PG' | 'Room' | 'Hotel')[] = ['Hostel', 'PG', 'Room', 'Hotel'];
export const allCities = ['Noida', 'Greater Noida'];
