import type { Property } from './types';

export const properties: Property[] = [
  {
    id: '1',
    title: 'Cozy Student Room near Campus',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'student room',
    price: 6000,
    location: 'Knowledge Park III, Greater Noida',
    city: 'Greater Noida',
    rating: 4.5,
    reviews: 23,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'AC', 'Housekeeping', 'CCTV'],
    description: 'A cozy and fully furnished room perfect for students looking for a quiet place to study and relax. Located just minutes away from the main campus.',
    roomOptions: [
      { occupancy: 'Single', price: 9000 },
      { occupancy: 'Double', price: 6000 },
    ],
    map: {
      lat: 28.4744,
      lng: 77.5050,
      nearby: [
        { name: 'Metro Station', distance: '400m' },
        { name: 'GL Bajaj Institute', distance: '1.2km' },
      ],
    },
    status: 'approved',
    ownerId: 'dummyOwner1',
  },
  {
    id: '2',
    title: 'Modern Boys Hostel with Food',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'modern hostel',
    price: 12000,
    location: 'Sector 62, Noida',
    city: 'Noida',
    rating: 4.8,
    reviews: 58,
    type: 'Boys',
    category: 'Hostel',
    amenities: ['WiFi', 'Food', 'Parking', 'Laundry', 'Geyser'],
    description: 'State-of-the-art hostel for boys with all modern amenities. Includes three meals a day and high-speed internet. Secure and comfortable.',
    roomOptions: [
      { occupancy: 'Double', price: 12000 },
      { occupancy: 'Triple', price: 10000 },
    ],
     map: {
      lat: 28.618,
      lng: 77.371,
      nearby: [
        { name: 'Sector 62 Metro', distance: '500m' },
        { name: 'IIM Lucknow (Noida Campus)', distance: '1km' },
      ],
    },
    status: 'approved',
    ownerId: 'dummyOwner2',
  },
  {
    id: '3',
    title: 'Spacious Girls PG with AC',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'spacious room',
    price: 10000,
    location: 'Alpha I, Greater Noida',
    city: 'Greater Noida',
    rating: 4.2,
    reviews: 15,
    type: 'Girls',
    category: 'PG',
    amenities: ['WiFi', 'AC', 'Food', 'CCTV'],
    description: 'A safe and spacious paying guest accommodation for girls. Features air-conditioned rooms and home-style food. 24/7 security.',
    roomOptions: [
        { occupancy: 'Single', price: 12000 },
        { occupancy: 'Double', price: 10000 },
    ],
    map: {
        lat: 28.464,
        lng: 77.514,
        nearby: [
            { name: 'Alpha 1 Metro', distance: '800m' },
            { name: 'Sharda University', distance: '2.5km' },
        ],
    },
    status: 'approved',
    ownerId: 'dummyOwner3',
  },
  {
    id: '4',
    title: 'Budget Hotel for Short Stays',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'budget hotel',
    price: 15000,
    location: 'Sector 18, Noida',
    city: 'Noida',
    rating: 4.0,
    reviews: 42,
    type: 'Co-ed',
    category: 'Hotel',
    amenities: ['WiFi', 'AC', 'Parking', 'Laundry'],
    description: 'Comfortable and affordable hotel rooms for short-term stays. Ideal for students and employees visiting for exams or interviews.',
    roomOptions: [
        { occupancy: 'Single', price: 15000 },
    ],
    map: {
        lat: 28.570,
        lng: 77.323,
        nearby: [
            { name: 'Sector 18 Metro', distance: '200m' },
            { name: 'DLF Mall of India', distance: '300m' },
        ],
    },
    status: 'approved',
    ownerId: 'dummyOwner4',
  },
  {
    id: '5',
    title: 'Premium Student Hostel',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'premium hostel',
    price: 18000,
    location: 'Knowledge Park II, Greater Noida',
    city: 'Greater Noida',
    rating: 4.9,
    reviews: 99,
    type: 'Co-ed',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food', 'Parking', 'Laundry', 'Housekeeping', 'CCTV'],
    description: 'Experience luxury living in our premium student hostel. Comes with a gym, recreational areas, and top-notch security.',
    roomOptions: [
        { occupancy: 'Single', price: 22000 },
        { occupancy: 'Double', price: 18000 },
    ],
    map: {
        lat: 28.470,
        lng: 77.498,
        nearby: [
            { name: 'Knowledge Park II Metro', distance: '100m' },
            { name: 'Galgotias University', distance: '500m' },
        ],
    },
    status: 'approved',
    ownerId: 'dummyOwner5',
  },
  {
    id: '6',
    title: 'Affordable PG for Students',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'student pg',
    price: 7500,
    location: 'Sector 12, Noida',
    city: 'Noida',
    rating: 3.8,
    reviews: 31,
    type: 'Boys',
    category: 'PG',
    amenities: ['WiFi', 'Food'],
    description: 'A budget-friendly PG for male students. Clean rooms, decent food, and a friendly environment. Close to the metro station.',
    roomOptions: [
        { occupancy: 'Double', price: 8500 },
        { occupancy: 'Triple', price: 7500 },
    ],
    map: {
        lat: 28.594,
        lng: 77.340,
        nearby: [
            { name: 'Sector 16 Metro', distance: '1.5km' },
        ],
    },
    status: 'approved',
    ownerId: 'dummyOwner6',
  },
  {
    id: '7',
    title: 'Independent Room for Professionals',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'independent room',
    price: 11000,
    location: 'Beta II, Greater Noida',
    city: 'Greater Noida',
    rating: 4.6,
    reviews: 19,
    type: 'Co-ed',
    category: 'Room',
    amenities: ['WiFi', 'AC', 'Parking', 'Housekeeping'],
    description: 'A private, independent room suitable for working professionals or students who value their privacy. Includes a personal kitchenette.',
    roomOptions: [
        { occupancy: 'Single', price: 11000 },
    ],
    map: {
        lat: 28.455,
        lng: 77.518,
        nearby: [
            { name: 'Beta 1 Metro', distance: '1km' },
        ],
    },
    status: 'approved',
    ownerId: 'dummyOwner7',
  },
  {
    id: '8',
    title: 'Girls Hostel near Metro',
    image: 'https://placehold.co/600x400.png',
    images: [
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
      'https://placehold.co/800x600.png',
    ],
    dataAiHint: 'girls hostel',
    price: 13500,
    location: 'Sector 15, Noida',
    city: 'Noida',
    rating: 4.7,
    reviews: 67,
    type: 'Girls',
    category: 'Hostel',
    amenities: ['WiFi', 'AC', 'Food', 'CCTV', 'Laundry'],
    description: 'A well-maintained hostel for girls with excellent connectivity. Located just a 5-minute walk from the metro station. Safe and secure.',
    roomOptions: [
        { occupancy: 'Double', price: 13500 },
    ],
    map: {
        lat: 28.583,
        lng: 77.317,
        nearby: [
            { name: 'Sector 15 Metro', distance: '400m' },
        ],
    },
    status: 'approved',
    ownerId: 'dummyOwner8',
  },
];

export const allAmenities: ('WiFi' | 'AC' | 'Food' | 'Parking' | 'Laundry' | 'Geyser' | 'Housekeeping' | 'CCTV')[] = ['WiFi', 'AC', 'Food', 'Parking', 'Laundry', 'Geyser', 'Housekeeping', 'CCTV'];
export const allCategories: ('Hostel' | 'PG' | 'Room' | 'Hotel')[] = ['Hostel', 'PG', 'Room', 'Hotel'];
export const allCities = ['Noida', 'Greater Noida'];

    